import CarbocationLocalLLM
import Foundation

/// Decodes generated token pieces without repeatedly decoding the complete output buffer.
///
/// A token piece can end in the middle of a UTF-8 scalar. In that case the unresolved
/// suffix is retained and no text is published until a later piece completes it, matching
/// `String(data:encoding:)` on the complete generated byte buffer.
struct IncrementalUTF8Accumulator {
    private enum Validation {
        case valid
        case incomplete
        case invalid
    }

    private var unresolved = Data()
    private var isPermanentlyInvalid = false

    private(set) var isAtUTF8Boundary = true

    mutating func append(_ bytes: Data) -> String {
        guard !bytes.isEmpty else { return "" }
        guard !isPermanentlyInvalid else {
            isAtUTF8Boundary = false
            return ""
        }

        unresolved.append(bytes)
        switch Self.validateUTF8Prefix(unresolved) {
        case .incomplete:
            isAtUTF8Boundary = false
            return ""
        case .invalid:
            isPermanentlyInvalid = true
            unresolved.removeAll(keepingCapacity: false)
            isAtUTF8Boundary = false
            return ""
        case .valid:
            break
        }

        let decoded = String(decoding: unresolved, as: UTF8.self)

        unresolved.removeAll(keepingCapacity: true)
        isAtUTF8Boundary = true
        return decoded
    }

    private static func validateUTF8Prefix(_ data: Data) -> Validation {
        let bytes = Array(data)
        var index = 0

        while index < bytes.count {
            let first = bytes[index]
            if first <= 0x7F {
                index += 1
                continue
            }

            let length: Int
            let secondRange: ClosedRange<UInt8>
            switch first {
            case 0xC2...0xDF:
                length = 2
                secondRange = 0x80...0xBF
            case 0xE0:
                length = 3
                secondRange = 0xA0...0xBF
            case 0xE1...0xEC, 0xEE...0xEF:
                length = 3
                secondRange = 0x80...0xBF
            case 0xED:
                length = 3
                secondRange = 0x80...0x9F
            case 0xF0:
                length = 4
                secondRange = 0x90...0xBF
            case 0xF1...0xF3:
                length = 4
                secondRange = 0x80...0xBF
            case 0xF4:
                length = 4
                secondRange = 0x80...0x8F
            default:
                return .invalid
            }

            guard index + 1 < bytes.count else { return .incomplete }
            guard secondRange.contains(bytes[index + 1]) else { return .invalid }
            if length > 2 {
                guard index + 2 < bytes.count else { return .incomplete }
                guard (0x80...0xBF).contains(bytes[index + 2]) else { return .invalid }
            }
            if length > 3 {
                guard index + 3 < bytes.count else { return .incomplete }
                guard (0x80...0xBF).contains(bytes[index + 3]) else { return .invalid }
            }
            index += length
        }

        return .valid
    }
}

/// Reports only newly completed literal matches while retaining a bounded suffix.
private struct IncrementalLiteralCompletionDetector {
    private let literals: [String]
    private let maximumDecomposedScalarLength: Int
    private var tail = ""

    init(_ literals: [String]) {
        self.literals = literals.filter { !$0.isEmpty }
        maximumDecomposedScalarLength = self.literals.map {
            $0.decomposedStringWithCanonicalMapping.unicodeScalars.count
        }.max() ?? 0
    }

    mutating func append(_ text: String) -> Bool {
        guard !text.isEmpty, maximumDecomposedScalarLength > 0 else { return false }

        let appendBoundaryUTF8Offset = tail.utf8.count
        let combined = tail + text
        var completed = false

        for literal in literals {
            var searchRange = combined.startIndex..<combined.endIndex
            while let range = combined.range(of: literal, range: searchRange) {
                let upperUTF8Offset = combined.utf8.distance(
                    from: combined.utf8.startIndex,
                    to: range.upperBound.samePosition(in: combined.utf8)!
                )
                if upperUTF8Offset > appendBoundaryUTF8Offset {
                    completed = true
                    break
                }
                guard range.upperBound < combined.endIndex else { break }
                searchRange = range.upperBound..<combined.endIndex
            }
            if completed { break }
        }

        let retainedScalars = max(0, maximumDecomposedScalarLength - 1)
        let scalarView = combined.unicodeScalars
        let tailStart = scalarView.index(
            scalarView.endIndex,
            offsetBy: -min(retainedScalars, scalarView.count)
        )
        tail = String(scalarView[tailStart...])
        return completed
    }
}

/// Incremental equivalent of `balancedJSONValueRange`: it starts at the first object or
/// array opener, honors JSON string escaping, and permanently rejects mismatched nesting.
private struct IncrementalBalancedJSONDetector {
    private enum State: Equatable {
        case searching
        case collecting
        case invalid
        case complete
    }

    private var state: State = .searching
    private var expectedClosers: [Character] = []
    private var isInsideString = false
    private var isEscaped = false

    mutating func append(_ text: String) -> Bool {
        guard !text.isEmpty, state != .invalid, state != .complete else { return false }

        for character in text {
            if state == .searching {
                if character == "{" {
                    state = .collecting
                    expectedClosers = ["}"]
                } else if character == "[" {
                    state = .collecting
                    expectedClosers = ["]"]
                }
                continue
            }

            if isEscaped {
                isEscaped = false
                continue
            }
            if character == "\\" && isInsideString {
                isEscaped = true
                continue
            }
            if character == "\"" {
                isInsideString.toggle()
                continue
            }

            guard !isInsideString else { continue }
            if character == "{" {
                expectedClosers.append("}")
            } else if character == "[" {
                expectedClosers.append("]")
            } else if character == "}" || character == "]" {
                guard expectedClosers.last == character else {
                    state = .invalid
                    return false
                }
                expectedClosers.removeLast()
                if expectedClosers.isEmpty {
                    state = .complete
                    return true
                }
            }
        }

        return false
    }
}

/// Captures successive balanced JSON values with absolute UTF-8 offsets. Unlike the
/// visibility candidate tracker, this also follows objects whose first key is not a tool
/// key, because a later key can still make the completed value a valid tool call.
private struct IncrementalBalancedJSONCaptureDetector {
    struct Completion {
        var startUTF8Offset: Int
        var text: String
    }

    private enum State {
        case searching
        case collecting
        case invalid
    }

    private var state: State = .searching
    private var expectedClosers: [Character] = []
    private var isInsideString = false
    private var isEscaped = false
    private var captureStartUTF8Offset = 0
    private var capturedText = ""

    mutating func append(
        _ text: String,
        startingAtUTF8Offset startUTF8Offset: Int
    ) -> [Completion] {
        guard !text.isEmpty, state != .invalid else { return [] }

        var completions: [Completion] = []
        var index = text.startIndex
        var utf8Offset = startUTF8Offset
        while index < text.endIndex {
            let next = text.index(after: index)
            let fragment = text[index..<next]
            let character = text[index]
            let fragmentUTF8Count = fragment.utf8.count

            if state == .searching {
                if character == "{" || character == "[" {
                    state = .collecting
                    captureStartUTF8Offset = utf8Offset
                    capturedText = String(fragment)
                    expectedClosers = [character == "{" ? "}" : "]"]
                    isInsideString = false
                    isEscaped = false
                }
                utf8Offset += fragmentUTF8Count
                index = next
                continue
            }

            capturedText.append(contentsOf: fragment)
            if isEscaped {
                isEscaped = false
            } else if character == "\\" && isInsideString {
                isEscaped = true
            } else if character == "\"" {
                isInsideString.toggle()
            } else if !isInsideString {
                if character == "{" {
                    expectedClosers.append("}")
                } else if character == "[" {
                    expectedClosers.append("]")
                } else if character == "}" || character == "]" {
                    guard expectedClosers.last == character else {
                        state = .invalid
                        return completions
                    }
                    expectedClosers.removeLast()
                    if expectedClosers.isEmpty {
                        completions.append(Completion(
                            startUTF8Offset: captureStartUTF8Offset,
                            text: capturedText
                        ))
                        state = .searching
                        capturedText = ""
                    }
                }
            }

            utf8Offset += fragmentUTF8Count
            index = next
        }

        return completions
    }
}

/// Keeps the hot generation-loop analysis incremental. The existing whole-string parsers
/// remain the source of truth and are invoked only when a bounded matcher or JSON state
/// proves that their observable result may have changed.
struct IncrementalGenerationParser {
    struct Snapshot {
        var phase: LLMStreamContentPhase
        var structuredPhase: LlamaEngine.StructuredOutputPhase?
        var boundary: LlamaEngine.GenerationBoundary?
    }

    private let streamPhasePlan: LlamaEngine.StreamPhasePlan
    private let structuredOutputPlan: LlamaEngine.StructuredOutputPlan?
    private let stopSequences: [String]
    private let stopAtBalancedJSON: Bool

    private var phaseLiteralDetector: IncrementalLiteralCompletionDetector
    private var thinkingCloseDetector: IncrementalLiteralCompletionDetector
    private var structuredLiteralDetector: IncrementalLiteralCompletionDetector
    private var stopLiteralDetector: IncrementalLiteralCompletionDetector
    private var nativeEndDetector = IncrementalLiteralCompletionDetector(
        LlamaNativeToolProtocol.allCases.map(\.endMarker)
    )
    private var jsonDetector = IncrementalBalancedJSONDetector()
    private var structuredJSONDetector = IncrementalBalancedJSONDetector()
    private var isStructuredJSONActive = false

    private(set) var phase: LLMStreamContentPhase
    private(set) var structuredPhase: LlamaEngine.StructuredOutputPhase?
    private(set) var boundary: LlamaEngine.GenerationBoundary?
    private var finalPhaseMayStartAnotherLeadingBlock: Bool

    init(
        streamPhasePlan: LlamaEngine.StreamPhasePlan,
        structuredOutputPlan: LlamaEngine.StructuredOutputPlan?,
        stopSequences: [String],
        stopAtBalancedJSON: Bool
    ) {
        self.streamPhasePlan = streamPhasePlan
        self.structuredOutputPlan = structuredOutputPlan
        self.stopSequences = stopSequences
        self.stopAtBalancedJSON = stopAtBalancedJSON

        let phaseLiterals = streamPhasePlan.continuingOpenThinkingPairs.map(\.close)
            + streamPhasePlan.profile.thinkingPairs.flatMap { [$0.open, $0.close] }
            + streamPhasePlan.profile.allFinalMarkers
        phaseLiteralDetector = IncrementalLiteralCompletionDetector(phaseLiterals)
        thinkingCloseDetector = IncrementalLiteralCompletionDetector(
            streamPhasePlan.continuingOpenThinkingPairs.map(\.close)
                + streamPhasePlan.profile.thinkingPairs.map(\.close)
        )

        let structuredLiterals = structuredOutputPlan.map { plan in
            plan.continuingOpenThinkingPairs.map(\.close)
                + plan.profile.thinkingPairs.flatMap { [$0.open, $0.close] }
                + plan.profile.allFinalMarkers
        } ?? []
        structuredLiteralDetector = IncrementalLiteralCompletionDetector(structuredLiterals)
        stopLiteralDetector = IncrementalLiteralCompletionDetector(stopSequences)

        phase = LlamaEngine.streamContentPhase(in: "", plan: streamPhasePlan)
        finalPhaseMayStartAnotherLeadingBlock = phase == .final
        structuredPhase = structuredOutputPlan.map {
            LlamaEngine.structuredOutputPhase(in: "", plan: $0)
        }
    }

    mutating func append(_ appendedText: String, fullText: String) -> Snapshot {
        guard !appendedText.isEmpty, boundary == nil else {
            return Snapshot(phase: phase, structuredPhase: structuredPhase, boundary: boundary)
        }

        let phaseLiteralCompleted = phaseLiteralDetector.append(appendedText)
        let thinkingCloseCompleted = thinkingCloseDetector.append(appendedText)
        switch phase {
        case .final:
            if phaseLiteralCompleted
                || (finalPhaseMayStartAnotherLeadingBlock
                    && appendedText.contains(where: { !$0.isWhitespace })) {
                phase = LlamaEngine.streamContentPhase(in: fullText, plan: streamPhasePlan)
                if phase == .final,
                   !thinkingCloseCompleted,
                   appendedText.contains(where: { !$0.isWhitespace }) {
                    finalPhaseMayStartAnotherLeadingBlock = false
                }
            }
        case .unknown:
            if appendedText.contains(where: { !$0.isWhitespace }) {
                phase = LlamaEngine.streamContentPhase(in: fullText, plan: streamPhasePlan)
            }
        case .thinking:
            if phaseLiteralCompleted {
                phase = LlamaEngine.streamContentPhase(in: fullText, plan: streamPhasePlan)
            }
        }
        if thinkingCloseCompleted, phase == .final {
            finalPhaseMayStartAnotherLeadingBlock = true
        }

        let stopCompleted = stopLiteralDetector.append(appendedText)
        let nativeEnvelopeCompleted = stopAtBalancedJSON
            ? nativeEndDetector.append(appendedText)
            : false
        var jsonCompleted = false
        var structuredSyntaxChanged = false

        if let plan = structuredOutputPlan {
            let literalCompleted = structuredLiteralDetector.append(appendedText)
            let hasJSONOpener = appendedText.contains("{") || appendedText.contains("[")
            let previousPhase = structuredPhase

            switch structuredPhase {
            case .thinking:
                structuredSyntaxChanged = literalCompleted
            case .awaitingFinal:
                structuredSyntaxChanged = literalCompleted || hasJSONOpener
            case .final, .complete, nil:
                break
            }

            if structuredSyntaxChanged {
                structuredPhase = LlamaEngine.structuredOutputPhase(in: fullText, plan: plan)
            }

            if stopAtBalancedJSON {
                if structuredPhase == .final, previousPhase != .final {
                    isStructuredJSONActive = true
                    structuredJSONDetector = IncrementalBalancedJSONDetector()
                    if let range = LlamaEngine.structuredFinalOutputSearchRange(
                        in: fullText,
                        plan: plan
                    ) {
                        jsonCompleted = structuredJSONDetector.append(String(fullText[range]))
                    }
                } else if isStructuredJSONActive, structuredPhase == .final {
                    jsonCompleted = structuredJSONDetector.append(appendedText)
                }
            }
        } else if stopAtBalancedJSON {
            jsonCompleted = jsonDetector.append(appendedText)
        }

        if stopCompleted || nativeEnvelopeCompleted || jsonCompleted || structuredSyntaxChanged {
            boundary = if let plan = structuredOutputPlan {
                LlamaEngine.firstStructuredGenerationBoundary(
                    in: fullText,
                    stopSequences: stopSequences,
                    stopAtBalancedJSON: stopAtBalancedJSON,
                    plan: plan
                )
            } else {
                LlamaEngine.firstGenerationBoundary(
                    in: fullText,
                    stopSequences: stopSequences,
                    stopAtBalancedJSON: stopAtBalancedJSON
                )
            }
        }

        return Snapshot(phase: phase, structuredPhase: structuredPhase, boundary: boundary)
    }

    mutating func markStructuredOutputComplete() {
        structuredPhase = .complete
    }
}

/// Incrementally locates and parses tool protocol without searching all generated prose
/// after every token. Whole-string interpreter calls are limited to a bounded probe or
/// the active tool capture itself at state transitions.
struct IncrementalToolStreamParser {
    struct Interception {
        var utf8Range: Range<Int>
        var calls: [LLMToolCall]
    }

    struct Snapshot {
        var captureStartUTF8Offset: Int?
        var visiblePrefixUTF8Count: Int
        var completed: Interception?
        var pendingNative: Interception?
    }

    private enum CandidateKind {
        case undecided
        case native
        case json
    }

    private struct WhitespaceBraceAnchor {
        var startUTF8Offset: Int
        var text: String
    }

    private static let nativeStartMarkers = LlamaNativeToolProtocol.allCases.map(\.startMarker)
    private static let nativeEndMarkers = LlamaNativeToolProtocol.allCases.map(\.endMarker)
    private static let jsonKeys = [
        #""tool_calls""#,
        #""function""#,
        #""name""#,
        #""tool_name""#,
        #""parameters""#,
        #""arguments""#,
        #""args""#,
        #""tool_call_id""#
    ]
    private static let probeCharacterLimit = 64

    private var totalUTF8Count = 0
    private var probeTail = ""
    private var whitespaceBraceAnchor: WhitespaceBraceAnchor?

    private var candidateStartUTF8Offset: Int?
    private var candidateText = ""
    private var candidateKind: CandidateKind = .undecided
    private var candidateNativeProtocol: LlamaNativeToolProtocol?
    private var candidateJSONDetector = IncrementalBalancedJSONDetector()
    private var allJSONCaptureDetector = IncrementalBalancedJSONCaptureDetector()
    private var candidateNativeEndDetector = IncrementalLiteralCompletionDetector(
        IncrementalToolStreamParser.nativeEndMarkers
    )
    private var nestedNativeStartDetector = IncrementalLiteralCompletionDetector(
        IncrementalToolStreamParser.nativeStartMarkers
    )
    private var nestedNativeEndDetector = IncrementalLiteralCompletionDetector(
        IncrementalToolStreamParser.nativeEndMarkers
    )
    private var nestedNativeStartUTF8Offset: Int?
    private var nestedNativeText = ""
    private var nestedNativeProtocol: LlamaNativeToolProtocol?
    private var nestedNativeSearchInvalidated = false
    private var pendingNative: Interception?
    private var pendingNativeSuffix = ""
    private var completed: Interception?
    private var needsLegacyReconciliation = false

    static func shouldPreserveCaptureBudget(
        in fullText: String,
        captureStartUTF8Offset: Int
    ) -> Bool {
        guard captureStartUTF8Offset >= 0,
              captureStartUTF8Offset <= fullText.utf8.count else { return false }
        let capturedText = String(
            fullText[fullText.index(atUTF8Offset: captureStartUTF8Offset)...]
        )
        return LlamaToolStreamInterpreter.isPotentialStartedToolCall(in: capturedText)
    }

    mutating func append(_ appendedText: String, fullText: String) -> Snapshot {
        guard !appendedText.isEmpty, completed == nil else { return snapshot }

        let previousUTF8Count = totalUTF8Count
        totalUTF8Count += appendedText.utf8.count
        let completedJSONValues = allJSONCaptureDetector.append(
            appendedText,
            startingAtUTF8Offset: previousUTF8Count
        )
        needsLegacyReconciliation = !completedJSONValues.isEmpty

        if candidateStartUTF8Offset != nil {
            candidateText.append(contentsOf: appendedText)
            advanceCandidate(appendedText: appendedText)
            evaluateCompletedJSONValues(completedJSONValues)
            return finishAppend(fullText: fullText)
        }

        if var anchor = whitespaceBraceAnchor {
            anchor.text.append(contentsOf: appendedText)
            if appendedText.allSatisfy(\.isWhitespace) {
                whitespaceBraceAnchor = anchor
                updateProbeTail(with: probeTail + appendedText)
                evaluateCompletedJSONValues(completedJSONValues)
                return finishAppend(fullText: fullText)
            }

            whitespaceBraceAnchor = nil
            seedCandidateIfPresent(in: anchor.text, baseUTF8Offset: anchor.startUTF8Offset)
            evaluateCompletedJSONValues(completedJSONValues)
            return finishAppend(fullText: fullText)
        }

        let sourceBase = previousUTF8Count - probeTail.utf8.count
        seedCandidateIfPresent(
            in: probeTail + appendedText,
            baseUTF8Offset: sourceBase
        )
        evaluateCompletedJSONValues(completedJSONValues)
        return finishAppend(fullText: fullText)
    }

    private mutating func finishAppend(fullText: String) -> Snapshot {
        if needsLegacyReconciliation {
            reconcileWithLegacy(fullText: fullText)
        }
        return snapshot
    }

    private var snapshot: Snapshot {
        let captureStart = [
            candidateStartUTF8Offset,
            completed?.utf8Range.lowerBound
        ].compactMap { $0 }.min()
        return Snapshot(
            captureStartUTF8Offset: captureStart,
            visiblePrefixUTF8Count: captureStart ?? totalUTF8Count,
            completed: completed,
            pendingNative: pendingNative
        )
    }

    private mutating func seedCandidateIfPresent(
        in source: String,
        baseUTF8Offset: Int
    ) {
        guard let capture = LlamaToolStreamInterpreter.startedToolCall(in: source) else {
            candidateStartUTF8Offset = nil
            candidateText = ""
            candidateKind = .undecided
            candidateNativeProtocol = nil
            pendingNative = nil
            pendingNativeSuffix = ""
            rememberWhitespaceBraceAnchor(in: source, baseUTF8Offset: baseUTF8Offset)
            updateProbeTail(with: source)
            return
        }

        let localStart = source.utf8.distance(
            from: source.utf8.startIndex,
            to: capture.range.lowerBound.samePosition(in: source.utf8)!
        )
        candidateStartUTF8Offset = baseUTF8Offset + localStart
        candidateText = String(source[capture.range.lowerBound...])
        candidateKind = .undecided
        candidateNativeProtocol = nil
        pendingNative = nil
        pendingNativeSuffix = ""
        whitespaceBraceAnchor = nil
        classifyOrReleaseCandidate()
    }

    private mutating func advanceCandidate(appendedText: String) {
        switch candidateKind {
        case .undecided:
            classifyOrReleaseCandidate()
        case .native:
            let completedEnd = candidateNativeEndDetector.append(appendedText)
            if completedEnd {
                evaluateNativeCandidate()
            } else if pendingNative != nil {
                appendPendingNativeSuffix(appendedText)
                if !isPotentialNativeSiblingSuffix(pendingNativeSuffix) {
                    evaluateNativeCandidate()
                }
            }
        case .json:
            advanceNestedNative(appendedText: appendedText)
            if candidateJSONDetector.append(appendedText) {
                releaseCompletedJSONCandidate()
            }
        }
    }

    private mutating func classifyOrReleaseCandidate() {
        guard LlamaToolStreamInterpreter.isPotentialStartedToolCall(in: candidateText) else {
            releaseAndReseedCandidate()
            return
        }

        if let protocolKind = LlamaNativeToolProtocol.allCases.first(where: {
            candidateText.hasPrefix($0.startMarker)
        }) {
            candidateKind = .native
            candidateNativeProtocol = protocolKind
            candidateNativeEndDetector = IncrementalLiteralCompletionDetector(
                [protocolKind.endMarker]
            )
            if candidateNativeEndDetector.append(candidateText) {
                evaluateNativeCandidate()
            }
            return
        }

        let afterBrace: String
        if candidateText.first == "{" {
            afterBrace = candidateText.dropFirst()
                .trimmingCharacters(in: .whitespacesAndNewlines)
        } else if candidateText.first == "[" {
            let afterBracket = candidateText.dropFirst().drop(while: \.isWhitespace)
            guard afterBracket.first == "{" else { return }
            afterBrace = afterBracket.dropFirst()
                .trimmingCharacters(in: .whitespacesAndNewlines)
        } else {
            return
        }
        guard Self.jsonKeys.contains(where: { afterBrace.hasPrefix($0) }) else { return }

        candidateKind = .json
        candidateJSONDetector = IncrementalBalancedJSONDetector()
        resetNestedNativeTracking()
        advanceNestedNative(appendedText: candidateText)
        if candidateJSONDetector.append(candidateText) {
            releaseCompletedJSONCandidate()
        }
    }

    private mutating func evaluateNativeCandidate() {
        needsLegacyReconciliation = true
        if let local = LlamaToolStreamInterpreter.completedToolCallForStreaming(in: candidateText) {
            mergeCompleted(globalInterception(from: local))
            pendingNative = nil
            pendingNativeSuffix = ""
            return
        }

        if let local = LlamaToolStreamInterpreter.pendingNativeToolCallBatch(in: candidateText) {
            let interception = globalInterception(from: local)
            pendingNative = interception
            if let upper = local.range.upperBound.samePosition(in: candidateText.utf8) {
                pendingNativeSuffix = boundedPendingNativeSuffix(from: String(
                    decoding: candidateText.utf8[upper...],
                    as: UTF8.self
                ))
            } else {
                pendingNativeSuffix = ""
            }
        } else {
            pendingNative = nil
            pendingNativeSuffix = ""
            releaseAndReseedCandidate()
        }
    }

    private mutating func evaluateCompletedJSONValues(
        _ values: [IncrementalBalancedJSONCaptureDetector.Completion]
    ) {
        var shouldReleaseActiveJSON = false
        for value in values {
            if let pendingNative,
               pendingNative.utf8Range.lowerBound < value.startUTF8Offset {
                continue
            }
            if let local = LlamaToolStreamInterpreter.completedToolCallForStreaming(
                in: value.text
            ) {
                mergeCompleted(globalInterception(
                    from: local,
                    text: value.text,
                    baseUTF8Offset: value.startUTF8Offset
                ))
                pendingNative = nil
                continue
            }
            if value.startUTF8Offset == candidateStartUTF8Offset,
               case .json = candidateKind {
                shouldReleaseActiveJSON = true
            }
        }

        if shouldReleaseActiveJSON {
            releaseAndReseedCandidate()
        }
    }

    private mutating func mergeCompleted(_ interception: Interception) {
        if completed.map({ interception.utf8Range.lowerBound < $0.utf8Range.lowerBound }) ?? true {
            completed = interception
        }
    }

    private mutating func advanceNestedNative(appendedText: String) {
        guard !nestedNativeSearchInvalidated else { return }
        if nestedNativeStartUTF8Offset == nil {
            guard nestedNativeStartDetector.append(appendedText) else {
                return
            }
            guard let range = Self.firstNativeStartRange(in: candidateText) else { return }
            let localStart = candidateText.utf8.distance(
                from: candidateText.utf8.startIndex,
                to: range.lowerBound.samePosition(in: candidateText.utf8)!
            )
            nestedNativeStartUTF8Offset = (candidateStartUTF8Offset ?? 0) + localStart
            nestedNativeText = String(candidateText[range.lowerBound...])
            nestedNativeProtocol = LlamaNativeToolProtocol.matchingStart(
                of: candidateText[range.lowerBound...]
            )
            nestedNativeEndDetector = IncrementalLiteralCompletionDetector(
                nestedNativeProtocol.map { [$0.endMarker] } ?? Self.nativeEndMarkers
            )
            if nestedNativeEndDetector.append(nestedNativeText) {
                evaluateNestedNative()
            }
            return
        }

        nestedNativeText.append(contentsOf: appendedText)
        if nestedNativeEndDetector.append(appendedText) {
            evaluateNestedNative()
        } else if pendingNative != nil {
            appendPendingNativeSuffix(appendedText)
            if !isPotentialNativeSiblingSuffix(pendingNativeSuffix) {
                evaluateNestedNative()
            }
        }
    }

    private mutating func evaluateNestedNative() {
        needsLegacyReconciliation = true
        guard let base = nestedNativeStartUTF8Offset else { return }
        if let local = LlamaToolStreamInterpreter.completedToolCallForStreaming(
            in: nestedNativeText
        ) {
            mergeCompleted(globalInterception(
                from: local,
                text: nestedNativeText,
                baseUTF8Offset: base
            ))
            pendingNative = nil
            pendingNativeSuffix = ""
            return
        }
        if let local = LlamaToolStreamInterpreter.pendingNativeToolCallBatch(
            in: nestedNativeText
        ) {
            pendingNative = globalInterception(
                from: local,
                text: nestedNativeText,
                baseUTF8Offset: base
            )
            if let upper = local.range.upperBound.samePosition(in: nestedNativeText.utf8) {
                pendingNativeSuffix = boundedPendingNativeSuffix(from: String(
                    decoding: nestedNativeText.utf8[upper...],
                    as: UTF8.self
                ))
            }
            return
        }

        // The legacy parser only considers the envelope beginning at the
        // earliest native start marker. If that completed envelope is
        // malformed, later markers do not supersede it for this candidate.
        resetNestedNativeTracking(invalidated: true)
    }

    private mutating func resetNestedNativeTracking(invalidated: Bool = false) {
        nestedNativeStartDetector = IncrementalLiteralCompletionDetector(
            Self.nativeStartMarkers
        )
        nestedNativeEndDetector = IncrementalLiteralCompletionDetector(
            Self.nativeEndMarkers
        )
        nestedNativeStartUTF8Offset = nil
        nestedNativeText = ""
        nestedNativeProtocol = nil
        nestedNativeSearchInvalidated = invalidated
    }

    /// Re-runs the legacy interpreter only at a parser state transition. This
    /// preserves its whole-output precedence rules (notably the first native
    /// envelope and outer JSON ranges) without putting a full scan back on the
    /// ordinary per-token path.
    private mutating func reconcileWithLegacy(fullText: String) {
        let legacyCompleted = LlamaToolStreamInterpreter.completedToolCallForStreaming(
            in: fullText
        )
        let legacyPending = LlamaToolStreamInterpreter.pendingNativeToolCallBatch(
            in: fullText
        )
        let legacyCapture = LlamaToolStreamInterpreter.startedToolCall(in: fullText)

        candidateStartUTF8Offset = nil
        candidateText = ""
        candidateKind = .undecided
        candidateNativeProtocol = nil
        candidateJSONDetector = IncrementalBalancedJSONDetector()
        candidateNativeEndDetector = IncrementalLiteralCompletionDetector(
            Self.nativeEndMarkers
        )
        whitespaceBraceAnchor = nil
        pendingNative = nil
        pendingNativeSuffix = ""
        completed = nil
        resetNestedNativeTracking()

        if let legacyCapture {
            let captureStart = fullText.utf8.distance(
                from: fullText.utf8.startIndex,
                to: legacyCapture.range.lowerBound.samePosition(in: fullText.utf8)!
            )
            if legacyCompleted == nil {
                seedCandidateIfPresent(
                    in: String(fullText[legacyCapture.range.lowerBound...]),
                    baseUTF8Offset: captureStart
                )
            } else {
                // A completed inner value can coexist with an earlier
                // incomplete outer capture. Keep both offsets so the visible
                // prefix remains identical until interception finishes.
                candidateStartUTF8Offset = captureStart
                candidateText = String(fullText[legacyCapture.range.lowerBound...])
            }
        } else if legacyCompleted == nil {
            updateProbeTail(with: fullText)
            rememberWhitespaceBraceAnchor(in: fullText, baseUTF8Offset: 0)
        }

        completed = legacyCompleted.map {
            globalInterception(from: $0, text: fullText, baseUTF8Offset: 0)
        }
        pendingNative = legacyPending.map {
            globalInterception(from: $0, text: fullText, baseUTF8Offset: 0)
        }
        needsLegacyReconciliation = false
    }

    private func globalInterception(
        from local: LlamaToolStreamInterpreter.Interception
    ) -> Interception {
        globalInterception(
            from: local,
            text: candidateText,
            baseUTF8Offset: candidateStartUTF8Offset ?? 0
        )
    }

    private func globalInterception(
        from local: LlamaToolStreamInterpreter.Interception,
        text: String,
        baseUTF8Offset: Int
    ) -> Interception {
        let lower = text.utf8.distance(
            from: text.utf8.startIndex,
            to: local.range.lowerBound.samePosition(in: text.utf8)!
        )
        let upper = text.utf8.distance(
            from: text.utf8.startIndex,
            to: local.range.upperBound.samePosition(in: text.utf8)!
        )
        return Interception(
            utf8Range: (baseUTF8Offset + lower)..<(baseUTF8Offset + upper),
            calls: local.calls
        )
    }

    private mutating func releaseAndReseedCandidate() {
        guard let base = candidateStartUTF8Offset else { return }
        needsLegacyReconciliation = true
        let released = candidateText
        candidateStartUTF8Offset = nil
        candidateText = ""
        candidateKind = .undecided
        candidateNativeProtocol = nil
        pendingNative = nil
        pendingNativeSuffix = ""
        resetNestedNativeTracking()
        seedCandidateIfPresent(in: released, baseUTF8Offset: base)
    }

    private mutating func releaseCompletedJSONCandidate() {
        guard let base = candidateStartUTF8Offset,
              let range = LlamaEngine.balancedJSONValueRange(in: candidateText) else {
            return
        }
        needsLegacyReconciliation = true
        let upperOffset = candidateText.utf8.distance(
            from: candidateText.utf8.startIndex,
            to: range.upperBound.samePosition(in: candidateText.utf8)!
        )
        let completedText = candidateText
        let suffix = String(candidateText[range.upperBound...])
        candidateStartUTF8Offset = nil
        candidateText = ""
        candidateKind = .undecided
        candidateNativeProtocol = nil
        candidateJSONDetector = IncrementalBalancedJSONDetector()
        pendingNative = nil
        pendingNativeSuffix = ""
        resetNestedNativeTracking()

        if suffix.isEmpty {
            updateProbeTail(with: completedText)
            rememberWhitespaceBraceAnchor(
                in: completedText,
                baseUTF8Offset: base
            )
        } else {
            seedCandidateIfPresent(
                in: suffix,
                baseUTF8Offset: base + upperOffset
            )
        }
    }

    private func isPotentialNativeSiblingSuffix(_ suffix: String) -> Bool {
        guard !suffix.isEmpty else { return true }
        return activeNativeStartMarkers.contains {
            $0.hasPrefix(suffix) || suffix.hasPrefix($0)
        }
    }

    private mutating func appendPendingNativeSuffix(_ appendedText: String) {
        let markers = activeNativeStartMarkers
        guard !markers.contains(pendingNativeSuffix) else { return }

        let source = pendingNativeSuffix.isEmpty
            ? appendedText.drop(while: \.isWhitespace)
            : appendedText[...]
        let maximumMarkerLength = markers.map(\.count).max() ?? 0
        let capacity = max(0, maximumMarkerLength + 1 - pendingNativeSuffix.count)
        pendingNativeSuffix.append(contentsOf: source.prefix(capacity))
    }

    private func boundedPendingNativeSuffix(from text: String) -> String {
        let markers = activeNativeStartMarkers
        let trimmed = text.drop(while: \.isWhitespace)
        if let marker = markers.first(where: { trimmed.hasPrefix($0) }) {
            return marker
        }
        let maximumMarkerLength = markers.map(\.count).max() ?? 0
        return String(trimmed.prefix(maximumMarkerLength + 1))
    }

    private var activeNativeStartMarkers: [String] {
        switch candidateKind {
        case .native:
            return candidateNativeProtocol.map { [$0.startMarker] } ?? Self.nativeStartMarkers
        case .json:
            return nestedNativeProtocol.map { [$0.startMarker] } ?? Self.nativeStartMarkers
        case .undecided:
            return Self.nativeStartMarkers
        }
    }

    private static func firstNativeStartRange(in text: String) -> Range<String.Index>? {
        nativeStartMarkers.compactMap { text.range(of: $0) }
            .min { $0.lowerBound < $1.lowerBound }
    }

    private mutating func rememberWhitespaceBraceAnchor(
        in source: String,
        baseUTF8Offset: Int
    ) {
        guard let brace = source.lastIndex(of: "{") else {
            whitespaceBraceAnchor = nil
            return
        }
        let afterBrace = source[source.index(after: brace)...]
        guard afterBrace.allSatisfy(\.isWhitespace) else {
            whitespaceBraceAnchor = nil
            return
        }

        let localStart = source.utf8.distance(
            from: source.utf8.startIndex,
            to: brace.samePosition(in: source.utf8)!
        )
        whitespaceBraceAnchor = WhitespaceBraceAnchor(
            startUTF8Offset: baseUTF8Offset + localStart,
            text: String(source[brace...])
        )
    }

    private mutating func updateProbeTail(with source: String) {
        probeTail = String(source.suffix(Self.probeCharacterLimit))
    }
}

extension String {
    func index(atUTF8Offset offset: Int) -> String.Index {
        let utf8Index = utf8.index(utf8.startIndex, offsetBy: offset)
        return String.Index(utf8Index, within: self) ?? endIndex
    }
}
